name: Atualizar Dashboard Geotab

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  atualizar-planilha:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pegar os arquivos do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar as bibliotecas necessárias
        run: pip install mygeotab gspread oauth2client

      - name: Rodar o script principal
        env:
          CREDENCIAIS_GCP: ${{ secrets.CREDENCIAIS_GCP }}
        run: python sheetsautomatico.py
