name: Atualizar Dashboard Geotab

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  atualizar-planilha:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pegar os arquivos do repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar as bibliotecas necessárias
        run: pip install mygeotab gspread oauth2client

      - name: Criar arquivo JSON de forma 100% segura
        env:
          CHAVE_JSON: ${{ secrets.CREDENCIAIS_GCP }}
        run: |
          python -c "import os; f = open('porjeto-rodar-online-geotab-133b08a54dd7.json', 'w'); f.write(os.environ['CHAVE_JSON']); f.close()"

      - name: Rodar o script principal
        run: python sheetsautomatico.py
